"""init

Revision ID: c7081c740c1c
Revises: 
Create Date: 2026-04-18 19:39:37.410321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7081c740c1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('s_bias', sa.Float(), nullable=True),
    sa.Column('d_score_baseline', sa.Float(), nullable=True),
    sa.Column('d_score_baseline_std', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clinical_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta_acc', sa.Float(), nullable=True, comment='Diagnostic accuracy delta vs baseline'),
    sa.Column('rule_adherence_rate', sa.Float(), nullable=True, comment='Fraction of hard nudges where user changed decision'),
    sa.Column('w_fatigue', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iat_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('d_score', sa.Float(), nullable=False),
    sa.Column('mean_rt_block3', sa.Float(), nullable=False),
    sa.Column('mean_rt_block6', sa.Float(), nullable=False),
    sa.Column('mean_rt_block4', sa.Float(), nullable=False),
    sa.Column('mean_rt_block7', sa.Float(), nullable=False),
    sa.Column('pooled_sd_blocks3_6', sa.Float(), nullable=False),
    sa.Column('pooled_sd_blocks4_7', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iat_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('is_practice', sa.Boolean(), nullable=False),
    sa.Column('stimulus_word', sa.String(length=128), nullable=False),
    sa.Column('stimulus_category', sa.String(length=64), nullable=False, comment="e.g. 'pleasant', 'unpleasant', 'target_a', 'target_b'"),
    sa.Column('correct_key', sa.String(length=8), nullable=False),
    sa.Column('response_key', sa.String(length=8), nullable=True),
    sa.Column('reaction_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('presented_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('tortuosity', sa.Float(), nullable=False, comment='τ = actual path length / straight-line displacement'),
    sa.Column('mean_velocity', sa.Float(), nullable=False),
    sa.Column('velocity_variance', sa.Float(), nullable=False),
    sa.Column('acceleration_variance', sa.Float(), nullable=False),
    sa.Column('stutter_count', sa.Integer(), nullable=False),
    sa.Column('tau_deviation', sa.Float(), nullable=False, comment='(τ - baseline_mean) / baseline_std'),
    sa.Column('time_on_task', sa.Float(), nullable=False),
    sa.Column('rs_classification', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_windows')
    op.drop_table('iat_trials')
    op.drop_table('iat_results')
    op.drop_table('clinical_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
