"""add_cases

Revision ID: ca8cb7a9f127
Revises: c7081c740c1c
Create Date: 2026-04-18 23:02:44.758016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8cb7a9f127'
down_revision: Union[str, Sequence[str], None] = 'c7081c740c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_label', sa.String(length=64), nullable=False),
    sa.Column('chief_complaint', sa.String(length=256), nullable=False),
    sa.Column('vitals_json', sa.Text(), nullable=False),
    sa.Column('objective_findings', sa.Text(), nullable=False),
    sa.Column('correct_decision', sa.String(length=16), nullable=False),
    sa.Column('is_counter_stereotypical', sa.Boolean(), nullable=False, comment='Experimental stimulus — demographically counter-stereotypical presentation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_counter_stereotypical', sa.Boolean(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['triage_cases.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_decisions')
    op.drop_table('triage_cases')
    # ### end Alembic commands ###
